id: P007907
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19132
  title: ཤུག་གསེབ་བཙུན་མའི་དགོན་གྱི་གཅོད་རྟའི་འབྱུང་ཁམས་དང་རྣམ་པར་དཔྱད་པ།
  author: ''
  volumes:
    09f0be076009404cb6478b741eb0d666:
      image_group_id: I8LS19134
      title: ''
      volume_number: 1
      total_pages: 266
ebook_metadata:
  title: ཤུག་གསེབ་བཙུན་མའི་དགོན་གྱི་གཅོད་རྟའི་འབྱུང་ཁམས་དང་རྣམ་པར་དཔྱད་པ།
  author: ''
  sku: P007907
  cover: cover.jpg
  layers:
  - pagination
