id: opecha:P007907
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19132
  title: ཤུག་གསེབ་བཙུན་མའི་དགོན་གྱི་གཅོད་རྟའི་འབྱུང་ཁམས་དང་རྣམ་པར་དཔྱད་པ།
  volume:
    f5232b044e874523a97a401174c5e4cf:
      image_group_id: I8LS19134
      title: Volume 1 of gcod rta/
      volume_number: 1
      total_pages: 266
  author: ''
ebook_metadata:
  title: ཤུག་གསེབ་བཙུན་མའི་དགོན་གྱི་གཅོད་རྟའི་འབྱུང་ཁམས་དང་རྣམ་པར་དཔྱད་པ།
  author: ''
  sku: P007907
  cover: cover.jpg
  layers:
  - pagination
