id: I6B75769F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T13:19:57+00:00'
last_modified: '2022-06-09T07:20:13.125207+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19132
  title: ཤུག་གསེབ་བཙུན་མའི་དགོན་གྱི་གཅོད་རྟའི་འབྱུང་ཁམས་དང་རྣམ་པར་དཔྱད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    545A:
      image_group_id: I8LS19134
      title: Volume 1 of gcod rta/
      total_pages: 266
      order: 1
      base_file: 545A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
